### PR TITLE
Code formatted and adapter updated to display two types of view holders

### PR DESCRIPTION
**Pull request by JeneaVranceanu**
Screenshot_20200616-184346

### CODE REVIEW

**Comment by JeneaVranceanu** [comment]
@matir85 you can review changes by pressing "Commits" below the title. Press "Merge pull request" to add these changes into the master branch.

**Comment by JeneaVranceanu** [comment]
The major change is the added sealed class:

```
sealed class Types(val rawType: Int) {
    object Title : Types(0)
    object Article : Types(1)

    companion object {
        fun from(rawType: Int) =
            when (rawType) {
                Title.rawType -> Title
                Article.rawType -> Article
                else -> throw RuntimeException("No such type")
            }
    }
}
```

Using sealed class you can be sure that you have only a confined number of types that extend it. In our case you can be sure that `Types` class can be either `Title` or `Article`. Nothing else can extend it out from this file. That is one of the rules of sealed classes. 

Thus, when you use `when` statements you can avoid `else` branch:

```
when (type) {
    is Title -> // do this
    is Article -> // do that
   // else branch not required
}
```

That sealed class just replaced your constants:

```
private const val TITLE_VIEW = 0
private const val ARTICLE_VIEW = 1
```

**Comment by JeneaVranceanu** [comment]
About `onCreateViewHolder` and `onBindViewHolder`.

Regarding the first one, the method body just is logically the same but I use `let` function from Kotlin standard library:

```
override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): RecyclerView.ViewHolder =
        LayoutInflater.from(parent.context).let { inflater ->
                // now using inflater we decide view holder type and create new view holder
            }
```

In `onBindViewHolder` we do just the same but without `LayoutInflater`. We decide item view type for given position and then apply required updates to the given view.

**Comment by matir85** [comment]
@JeneaVranceanu  For example, if I would like to add `Title` again in 14 items, just add `0, 14 -> Types.Title.rawType` in `getItemViewType` or do I need to modify anything else ???

**Comment by JeneaVranceanu** [comment]
@matir85 As an option that is possible. But in reality, no one would accept such implementation because adapter should not care where exactly in the list `Title`s and `Article`s are positioned. They must be always displayed correctly. 

The solution to this problem is quite simple. Instead of giving your adapter a list of `String`s you should create your own class, actually two classes, that will store all content related to an article and all content related to a title.

I would suggest implementing it like this:

```
sealed class BaseKodeksKarnyItem {
    abstract val title: String
}

data class Article(override val title: String, val content: String) : BaseKodeksKarnyItem()
data class Title(override val title: String) : BaseKodeksKarnyItem()
```

You will have two classes and by checking the type of `BaseKodeksKarnyItem` (whether it is Article or Title) you will create appropriate view holder.

I'll add one more PR.

**Pull request merged**
